server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  appenders:
    - type: console

serviceWizard:
  baseUrl: "http://localhost:8080"
  apiName: "Sample application"
  transformers:
    - type: angular
      moduleName: "todo"
      outputFilePath: "./output/js"
    - type: default_html
      outputFilePath: "./output/docs.html"
    - type: default_markdown
      outputFilePath: "./output/markdown.md"
